### ISSUE TITLE
Problem on parsed results of binary expression

### ISSUE THREAD

**Issue by landhero** [antlrjavaparser/antlr-java-parser#6]
Current version (1.0.15) cannot parse shift operators. Calling JavaParser.parse() will parse the '<<' as '<=' and '>>' as '<'. Besides, it seems that '>>>' cannot be parsed either. 

Sample input file:

    public class Debug{
    	public Debug(){
    		1 << 6; //1 <= 6
    		1 >> 6; //1 < 6
    	}
    }

**Comment by mikedehaan** [comment]
Thank you very much for your test case. This problem has been resolved in version 1.0.16.
