### ISSUE TITLE
antlr-java-parser don't include the license file

### ISSUE THREAD

**Issue by puntogil** [antlrjavaparser/antlr-java-parser#7]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by mikedehaan** [comment]
A LICENSE file is now included in the project root. Also updated the license notice in all source files.
