### ISSUE TITLE
maven build failed

### ISSUE THREAD

**Issue by pierre-luc** [antlrjavaparser/antlr-java-parser#8]
I cloned this repo and flowwed instructions from Readme.md
The step "mvn release:prepare" don't succeed.

  Failed tests: 
      TestAstPosition.ifStatementTest:39 Method body index start is incorrect. expected:<80> but was:<75>

I don't understand, because I don't change the source files.

**Comment by mikedehaan** [comment]
My apologies. These instructions are only for releasing the jar to the public maven repository. You should be able to run normal maven commands to build the jar locally:

mvn clean
mvn package
mvn install
...
